version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      groups:
          dev:
              dependency-type: development
          production:
              dependency-type: production

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
