version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      groups:
          update-types:
          - "minor"
          - "patch"
      schedule:
          interval: 'daily'
      reviewers:
          - 'izzqz'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      reviewers:
          - 'izzqz'
