version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/lib'
      schedule:
          interval: 'daily'
      reviewers:
          - 'izzqz'
      target-branch: 'dependabot'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      reviewers:
          - 'izzqz'
      target-branch: 'dependabot'
