image:
    file: .gitpod.Dockerfile
tasks:
    - name: Instaling deps
      init: npm install
      
    - name: Login to npm
      command: if [[ ! -z "${NPM_TOKEN}" ]]; thenprintf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n" >> /home/gitpod/.npmrc; fi
