name: Manual patch release

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Bump version
        id: bump-version
        run: echo "::set-output name=version::$(npm version patch)"
        
      - name: Debug
        run: |
          echo ${{ join(steps) }}
          echo ${{ steps.bump-version }}
          echo ${{ steps.bump-version.outputs }}
          echo ${{ steps.bump-version.outputs.version }}
      
      - name: Create draft release in repository
        run: gh release create ${{ steps.bump-version.outputs.version }} --generate-notes --draft --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
