name: Manual patch release

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Bump version
        id: bump-version
        run: echo "::set-output name=version::$(npm version patch --no-git-tag-version)"
        
      - name: Push version commit
        run: git push
        
      - name: Create draft release in repository
        run: gh release create ${{ steps.bump-version.outputs.version }} --target ${{ steps.bump-version.outputs.version }} --generate-notes --draft --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
