name: Publish release

on:
    workflow_dispatch:
        inputs:
            skip-ci:
                type: boolean
                description: Skip CI
                required: false
                default: false
    release:
        types: [published]

jobs:
    ci:
        name: CI
        if: ${{ inputs.skip-ci == false }}
        uses: zenfuse/zenfuse.js/.github/workflows/package-ci.yml@main

    publish-npm:
        name: Publish to npm
        needs: ci
        if: always() && (needs.CI.result == 'success' || needs.CI.result == 'skipped')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: 'https://registry.npmjs.org'
                  cache: npm

            - name: Install npm dependencies
              run: npm ci
              
            - name: Publish to npm registry
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish-gp:
        name: Publish to gp
        needs: ci
        if: always() && (needs.CI.result == 'success' || needs.CI.result == 'skipped')
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: 'https://npm.pkg.github.com'
                  cache: npm
            
            - name: Install npm dependencies
              run: npm ci
            
            - name: Publish to github registry
              run: |
                # Add organisation scope to package name
                echo "$( jq '.name = "@zenfuse/zenfuse"' package.json )" > package.json
                # And publish this boy 
                npm publish --@zenfuse:registry=https://npm.pkg.github.com

              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
