name: Package CI

on:
    workflow_dispatch:
        inputs:
            skip-lint:
                type: boolean
                description: Skip lint
                required: false
                default: false
    workflow_call:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        name: Lint files
        if: ${{ inputs.skip-lint == false }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: taiki-e/install-action@v2
              with:
                  tool: just

            - name: Set up Bun
              uses: antongolub/action-setup-bun@v1
              with:
                  cache: true

            - uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

            - name: Update npm to latest
              run: npm i -g npm@9 --registry=https://registry.npmjs.org

            - name: Install npm dependencies
              run: npm ci

            - name: Install docs dependencies
              run: cd www && bun install

            - name: Lint javascript files
              run: just eslint

    unit-tests:
        needs: lint
        if: always() && (needs.lint.result == 'success' || needs.lint.result == 'skipped')
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14, 16, 18]
        steps:
            - uses: actions/checkout@v4
            - uses: taiki-e/install-action@v2
              with:
                  tool: just
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Update npm to latest
              run: npm i -g npm@9 --registry=https://registry.npmjs.org

            - name: Install npm dependencies
              run: npm ci

            - name: Run unit tests
              run: just test-unit

    integration-tests:
        needs: [lint]
        if: always() && (needs.lint.result == 'success' || needs.lint.result == 'skipped')
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14, 16, 18]
        steps:
            - uses: actions/checkout@v4
            - uses: taiki-e/install-action@v2
              with:
                  tool: just
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Update npm to latest
              run: npm i -g npm@9 --registry=https://registry.npmjs.org

            - name: Install npm dependencies
              run: npm ci

            - name: Run integration tests
              run: just test-integration
