name: Publish release

on:
    workflow_dispatch:
        inputs:
            skip-ci:
                type: boolean
                description: Skip CI
                required: false
                default: false
    push:
        tags:
            - 'v*'

jobs:
    ci:
        name: CI
        if: ${{ inputs.skip-ci == false }}
        uses: zenfuse/zenfuse.js/.github/workflows/package-ci.yml@main

    publish-npm:
        name: Publish to npm
        needs: ci
        if: always() && (needs.CI.result == 'success' || needs.CI.result == 'skipped')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: 'https://registry.npmjs.org'
                  cache: npm

            - name: Install npm dependencies
              run: npm ci
              
            - name: Publish to npm registry
              run: |
                # Change publish registry
                echo "$(jq '.publishConfig.registry = "https://registry.npmjs.org"' package.json)" > package.json
                # Publish package
                npm publish --access public --dry-run
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish-gp:
        name: Publish to gp
        needs: ci
        if: always() && (needs.CI.result == 'success' || needs.CI.result == 'skipped')
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: 'https://npm.pkg.github.com'
                  cache: npm
            
            - name: Install npm dependencies
              run: npm ci
            
            - name: Publish to github registry
              run: |
                # Change publish registry
                echo "$(jq '.publishConfig.registry = "https://npm.pkg.github.com"' package.json)" > package.json
                # Add organisation scope to package name
                echo "$( jq '.name = "@zenfuse/zenfuse"' package.json )" > package.json
                # And publish this boy 
                npm publish --@zenfuse:registry=https://npm.pkg.github.com --dry-run

              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  
    release:
        needs: [publish-npm, publish-gp]
        name: Post new release
        runs-on: ubuntu-latest
        steps:
            - name: Post release
              run: gh release create ${{ github.ref_name }} --target main --generate-notes --prerelease;
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
            - name: Set output
              run: | 
                echo "### New release ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
